// js/prompts/constants.js

export const PROMPTS = {
    // Normal Mode
    SPARK_NORMAL_1: `VAIDIK!!VAIDIK`,
    FLUX_NORMAL_1_THINK: `VAIDIK!!VAIDIK`,
    FLUX_NORMAL_2_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_NORMAL_1_WEB: `VAIDIK!!VAIDIK`, 
    ORACLE_NORMAL_2_THINK: `VAIDIK!!VAIDIK`,
    ORACLE_NORMAL_3_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_NORMAL_4_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_NORMAL_5_RESPONSE: `VAIDIK!!VAIDIK`,

    // Learn Mode
    FLUX_LEARN_1_THINK: `VAIDIK!!VAIDIK`,
    FLUX_LEARN_2_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_LEARN_1_WEB: `VAIDIK!!VAIDIK`, 
    ORACLE_LEARN_2_THINK: `VAIDIK!!VAIDIK`,
    ORACLE_LEARN_3_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_LEARN_4_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_LEARN_5_RESPONSE: `VAIDIK!!VAIDIK`,

    // Quiz, Test, Mock Test
    ORACLE_QUIZ_1_WEB: `VAIDIK!!VAIDIK`, 
    ORACLE_QUIZ_2_THINK: `VAIDIK!!VAIDIK`,
    ORACLE_QUIZ_3_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_QUIZ_4_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_QUIZ_5_RESPONSE: `VAIDIK!!VAIDIK`,
    
    ORACLE_TEST_1_WEB: `VAIDIK!!VAIDIK`, 
    ORACLE_TEST_2_THINK: `VAIDIK!!VAIDIK`,
    ORACLE_TEST_3_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_TEST_4_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_TEST_5_RESPONSE: `VAIDIK!!VAIDIK`,
    
    ORACLE_MOCK_TEST_1_WEB: `VAIDIK!!VAIDIK`, 
    ORACLE_MOCK_TEST_2_THINK: `VAIDIK!!VAIDIK`,
    ORACLE_MOCK_TEST_3_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_MOCK_TEST_4_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_MOCK_TEST_5_RESPONSE: `VAIDIK!!VAIDIK`,

    // Deep Research
    RESEARCH_PLAN_AI_PLAN_GENERATION: `VAIDIK!!VAIDIK`,
    
    SPARK_RESEARCH_1_WEB: `VAIDIK!!VAIDIK`, 
    SPARK_RESEARCH_2_WEB: `VAIDIK!!VAIDIK`, 
    SPARK_RESEARCH_3_THINK: `VAIDIK!!VAIDIK`,
    SPARK_RESEARCH_4_RESPONSE: `VAIDIK!!VAIDIK`,
    SPARK_RESEARCH_5_RESPONSE: `VAIDIK!!VAIDIK`,
    SPARK_RESEARCH_6_RESPONSE: `VAIDIK!!VAIDIK`,
    SPARK_RESEARCH_7_RESPONSE: `VAIDIK!!VAIDIK`,
    
    FLUX_RESEARCH_1_WEB: `VAIDIK!!VAIDIK`, 
    FLUX_RESEARCH_2_WEB: `VAIDIK!!VAIDIK`, 
    FLUX_RESEARCH_3_WEB: `VAIDIK!!VAIDIK`, 
    FLUX_RESEARCH_4_WEB: `VAIDIK!!VAIDIK`, 
    FLUX_RESEARCH_5_THINK: `VAIDIK!!VAIDIK`,
    FLUX_RESEARCH_6_RESPONSE: `VAIDIK!!VAIDIK`,
    FLUX_RESEARCH_7_RESPONSE: `VAIDIK!!VAIDIK`,
    FLUX_RESEARCH_8_RESPONSE: `VAIDIK!!VAIDIK`,
    FLUX_RESEARCH_9_RESPONSE: `VAIDIK!!VAIDIK`,
    FLUX_RESEARCH_10_RESPONSE: `VAIDIK!!VAIDIK`,
    
    ORACLE_RESEARCH_1_WEB: `VAIDIK!!VAIDIK`, 
    ORACLE_RESEARCH_2_WEB: `VAIDIK!!VAIDIK`, 
    ORACLE_RESEARCH_3_THINK: `VAIDIK!!VAIDIK`,
    ORACLE_RESEARCH_4_WEB: `VAIDIK!!VAIDIK`, 
    ORACLE_RESEARCH_5_WEB: `VAIDIK!!VAIDIK`, 
    ORACLE_RESEARCH_6_WEB: `VAIDIK!!VAIDIK`, 
    ORACLE_RESEARCH_7_THINK: `VAIDIK!!VAIDIK`,
    ORACLE_RESEARCH_8_THINK: `VAIDIK!!VAIDIK`,
    ORACLE_RESEARCH_9_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_RESEARCH_10_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_RESEARCH_11_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_RESEARCH_12_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_RESEARCH_13_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_RESEARCH_14_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_RESEARCH_15_RESPONSE: `VAIDIK!!VAIDIK`,

    // Coding
    SPARK_CODE_1: `VAIDIK!!VAIDIK`,
    FLUX_CODE_1_THINK: `VAIDIK!!VAIDIK`,
    FLUX_CODE_1_RESPONSE: `VAIDIK!!VAIDIK`,
    FLUX_CODE_2_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_CODE_1_THINK: `VAIDIK!!VAIDIK`,
    ORACLE_CODE_2_THINK: `VAIDIK!!VAIDIK`,
    ORACLE_CODE_3_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_CODE_4_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_CODE_5_RESPONSE: `VAIDIK!!VAIDIK`,

    // Planning
    SPARK_PLAN_1: `VAIDIK!!VAIDIK`,
    FLUX_PLAN_1_THINK: `VAIDIK!!VAIDIK`,
    FLUX_PLAN_2_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_PLAN_1_THINK: `VAIDIK!!VAIDIK`,
    ORACLE_PLAN_2_RESPONSE: `VAIDIK!!VAIDIK`,
    ORACLE_PLAN_3_RESPONSE: `VAIDIK!!VAIDIK`
};
